CourseSubmission/Controllers/LoginController.cs
using CourseSubmission.Helpers.Services;
using CourseSubmission.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CourseSubmission.Controllers;

public class LoginController : Controller
{
    private readonly AuthService _authService;

    public LoginController(AuthService authService)
    {
        _authService = authService;
    }

    [HttpGet]
    public IActionResult Index(string ReturnUrl = null!)
    {
        var model = new UserLoginVM();
        if (ReturnUrl != null)
            model.ReturnUrl = ReturnUrl;
        
        return View(model);
    }


    [HttpPost]
    public async Task<IActionResult> Index(UserLoginVM model)
    {
        if (ModelState.IsValid)
        {
           if(await _authService.LoginAsync(model))
                return LocalRedirect(model.ReturnUrl);

         ModelState.AddModelError("", "Invalid credentials..please try again");
        }
        
        return View(model);
    }
}

CourseSubmission/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using CourseSubmission.ViewModels;
using CourseSubmission.Helpers.Services;

namespace CourseSubmission.Controllers;

public class RegisterController : Controller
{
  
    private readonly AuthService _authService;

    public RegisterController( AuthService authService)
    {
        _authService = authService;
    }
    

   

    [HttpGet]
    public IActionResult Index()
    {

        return View();
    }
    

    [HttpPost]
    public async Task<IActionResult> Index(UserSignUpVM model)
    {
        if (ModelState.IsValid)
        {
            if (await _authService.UserAldredyExistsAsync(model))
                ModelState.AddModelError("", "This email appear to be registred already..");

            if(await _authService.RegisterUserAsync(model))
            return RedirectToAction("Index", "Login"); 
            
                
            
        }
        return View(model);
    }
}

CourseSubmission/Views/Login/Index.cshtml
@model UserLoginVM

@{
    ViewData["Title"] = "Sign in";
}

<div class="signup-main">
    <h1>Sign in</h1>
    <form method="post" novalidate asp-route-ReturnUrl="@Model.ReturnUrl">
        <div asp-validation-summary="ModelOnly"></div>
        
        <div>
            <label asp-for="Email">E-mail</label>
            <input asp-for="Email" />
            <small><span asp-validation-for="Email"></span></small>
        </div>
        
        <div>
            <label asp-for="Password">Password</label>
            <input asp-for="Password" />
            <small><span asp-validation-for="Password"></span></small>
        </div>
        <div>
            <button type="submit">Sign in</button>
        </div>
    </form>
    <p>Not a member yet?  Register <a asp-action="Index" asp-controller="Register">here.</a></p>
</div>